# Generated by Django 5.2.9 on 2025-12-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
